services:
  - type: web
    name: booktrack-library
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/library-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: library
          property: CONNECTION_STRING
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: library
          property: USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: library
          property: PASSWORD

databases:
  - name: library
    engine: mysql
    version: 8
    plan: free
    
